In [150]:
%matplotlib inline

In [151]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm
import re

In [152]:
def IR_Flag(rate):
    if rate > .12:
        return True
    else:
        return False

In [153]:
def num_strip_rt(data):
    if '%' in data:
        data = data.rstrip('%')
        
    if "." in data:
        data = float(data)/100
        
    return data

In [154]:
def get_int_from_text(data):
#     data = re.search('[0-9]*', data).group(0)
    data = re.findall('[0-9]+', data) # produces a 1 item list
    
#     print("data is type {}".format(type(data)))
    
#     data = [x for x in data if x != '']

    try:
        return data[0]
    except: 
        return len(data)

In [155]:
# get loandata
raw_data = pd.read_csv('https://spark-public.s3.amazonaws.com/dataanalysis/loansData.csv')

In [156]:
#ask Kyle why this runs so slow

raw_data['Debt.To.Income.Ratio'] = [num_strip_rt(data) for index, data in raw_data['Debt.To.Income.Ratio'].iteritems()]

In [157]:
raw_data['Interest.Rate'] = [num_strip_rt(data) for index, data in raw_data['Interest.Rate'].iteritems()]

In [158]:
raw_data['Loan.Length'] = [get_int_from_text(data) for index, data in raw_data['Loan.Length'].iteritems()]

In [159]:
raw_data['Employment.Length'] = [get_int_from_text(data) for index, data in raw_data['Employment.Length'].iteritems()]

In [161]:
raw_data

,Amount.Requested,Amount.Funded.By.Investors,Interest.Rate,Loan.Length,Loan.Purpose,Debt.To.Income.Ratio,State,Home.Ownership,Monthly.Income,FICO.Range,Open.CREDIT.Lines,Revolving.CREDIT.Balance,Inquiries.in.the.Last.6.Months,Employment.Length
81174,20000,20000.00,0.0890,36,debt_consolidation,0.149,SC,MORTGAGE,6541.67,735-739,14,14272,2,1
99592,19200,19200.00,0.1212,36,debt_consolidation,0.2836,TX,MORTGAGE,4583.33,715-719,12,11140,1,2
80059,35000,35000.00,0.2198,60,debt_consolidation,0.2381,CA,MORTGAGE,11500.00,690-694,14,21977,1,2
15825,10000,9975.00,0.0999,36,debt_consolidation,0.143,KS,MORTGAGE,3833.33,695-699,10,9346,0,5
33182,12000,12000.00,0.1171,36,credit_card,0.1878,NJ,RENT,3195.00,695-699,11,14469,0,9
62403,6000,6000.00,0.1531,36,other,0.2005,CT,OWN,4891.67,670-674,17,10391,2,3
48808,10000,10000.00,0.0790,36,debt_consolidation,0.2609,MA,RENT,2916.67,720-724,10,15957,0,10
22090,33500,33450.00,0.1714,60,credit_card,0.147,LA,MORTGAGE,13863.42,705-709,12,27874,0,10
76404,14675,14675.00,0.1433,36,credit_card,0.2692,CA,RENT,3150.00,685-689,9,7246,1,8
15867,7000,7000.00,0.0691,36,credit_card,0.071,CA,RENT,5000.00,715-719,8,7612,0,3
94971,2000,2000.00,0.1972,36,moving,0.1029,FL,RENT,3575.00,670-674,10,12036,0,6
36911,10625,10625.00,0.1427,36,debt_consolidation,0.1254,CA,MORTGAGE,4250.00,665-669,14,10767,0,1
41200,28000,27975.00,0.2167,60,debt_consolidation,0.1307,CT,MORTGAGE,14166.67,670-674,12,10311,0,1
83869,35000,34950.00,0.0890,36,debt_consolidation,0.2046,CT,RENT,9166.67,735-739,19,21536,0,1
53853,9600,9600.00,0.0762,36,debt_consolidation,0.0345,DC,RENT,11250.00,725-729,13,4606,0,1
21399,25000,24975.00,0.1565,60,debt_consolidation,0.2199,CA,RENT,5416.67,730-734,6,13929,0,9
62127,10000,10000.00,0.1212,36,debt_consolidation,0.1772,CA,RENT,9000.00,695-699,18,20317,0,7
23446,14000,13900.25,0.1037,60,debt_consolidation,0.1195,OH,RENT,4333.33,740-744,6,7419,0,9
44987,10000,10000.00,0.0976,36,credit_card,0.0713,FL,RENT,2733.33,730-734,7,6112,2,3
17977,5200,5175.00,0.0999,60,debt_consolidation,0.1029,AL,MORTGAGE,3750.00,760-764,10,16094,0,1
86099,22000,21975.00,0.2198,36,debt_consolidation,0.1119,TX,MORTGAGE,6666.67,665-669,9,23124,0,10
99483,30000,30000.00,0.1905,60,credit_card,0.2125,FL,MORTGAGE,6250.00,695-699,12,34927,0,6
28798,6500,6500.00,0.1799,60,car,0.1963,FL,RENT,4100.00,665-669,11,11697,1,2
24168,17400,17400.00,0.1199,36,credit_card,0.1247,AZ,RENT,6833.33,695-699,7,26587,0,7
10356,4000,4000.00,0.1682,60,vacation,0.1371,GA,MORTGAGE,4500.00,670-674,5,20804,0,3
46027,7200,7200.00,0.0790,36,debt_consolidation,0.2482,TX,RENT,5416.67,705-709,8,12017,0,7
2238,8000,8000.00,0.1442,36,debt_consolidation,0.2463,MA,RENT,2964.17,675-679,9,8928,2,6
65278,8000,8000.00,0.1531,36,debt_consolidation,0.1546,CA,MORTGAGE,2916.67,675-679,13,7152,1,5
4227,3000,3000.00,0.0859,36,other,0.0372,MA,MORTGAGE,4167.00,765-769,4,7074,0,5
50182,14500,14500.00,0.0790,36,debt_consolidation,0.0485,GA,MORTGAGE,3958.33,760-764,4,9598,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84265,20000,20000.00,0.2295,60,debt_consolidation,0.071,NJ,RENT,6750.00,665-669,6,16104,1,7
80231,19000,19000.00,0.0790,36,debt_consolidation,0.0976,RI,MORTGAGE,5166.67,770-774,18,43617,2,10
49533,17300,17250.00,0.2245,60,wedding,0.0358,PA,MORTGAGE,5500.00,685-689,11,2306,3,4
102514,7000,711.54,0.1513,36,major_purchase,0.1891,CO,MORTGAGE,3833.00,650-654,13,12634,0,2
78618,7200,7200.00,0.1875,36,debt_consolidation,0.1621,MI,RENT,8333.33,660-664,8,28916,0,10
86953,10000,10000.00,0.1409,36,major_purchase,0.0971,CO,RENT,4583.33,675-679,6,3859,0,1
80129,4000,3925.00,0.1409,36,credit_card,0.1227,FL,MORTGAGE,8583.33,675-679,9,36943,1,10
85216,17500,17500.00,0.0890,36,debt_consolidation,0.1094,UT,MORTGAGE,25000.00,730-734,9,34545,0,6
38247,20000,20000.00,0.1171,36,credit_card,0.0958,SD,MORTGAGE,5416.67,725-729,12,18267,1,4
91245,16200,16200.00,0.1580,60,debt_consolidation,0.0792,PA,MORTGAGE,4833.33,680-684,12,12313,2,10
53041,10000,10000.00,0.0603,36,small_business,0.1303,FL,RENT,5000.00,760-764,8,3952,0,2
63051,27000,27000.00,0.0662,36,debt_consolidation,0.1221,OH,MORTGAGE,9250.00,810-814,12,4211,0,5
14446,4500,4475.00,0.0751,36,small_business,0.2027,VA,MORTGAGE,7075.50,720-724,15,68618,2,10
68628,15875,15875.00,0.1433,36,small_business,0.1744,MD,MORTGAGE,3416.67,675-679,11,15891,0,2
98758,15000,15000.00,0.1016,36,credit_card,0.2828,OH,MORTGAGE,6666.67,690-694,15,14880,0,10
13070,25000,24950.00,0.1075,36,debt_consolidation,0.2048,OR,MORTGAGE,7083.33,765-769,10,25429,0,6
45836,7000,7000.00,0.1727,36,other,0.1838,NY,OWN,2464.37,665-669,9,7089,0,3
52330,15000,15000.00,0.1999,36,wedding,0.1805,CA,RENT,8000.00,660-664,6,45976,1,2
48243,17000,17000.00,0.1581,36,debt_consolidation,0.1701,CO,RENT,3833.33,685-689,6,15484,1,6
63256,19075,19075.00,0.1875,36,debt_consolidation,0.1523,NY,RENT,5166.67,670-674,17,13749,3,10
42124,10000,10000.00,0.1171,36,debt_consolidation,0.084,CA,RENT,4500.00,710-714,8,8404,1,3
78043,8475,8475.00,0.0762,36,debt_consolidation,0.1588,CA,RENT,3983.33,720-724,9,6882,0,0
925,6400,6350.00,0.1008,36,debt_consolidation,0.0811,NJ,MORTGAGE,5166.67,710-714,5,5815,2,10
74047,30000,30000.00,0.2328,60,other,0.121,IL,MORTGAGE,7083.33,675-679,16,17969,1,10
49957,24000,23975.00,0.1465,36,debt_consolidation,0.1529,WA,MORTGAGE,6666.67,685-689,13,17521,0,5
23735,30000,29950.00,0.1677,60,debt_consolidation,0.1923,NY,MORTGAGE,9250.00,705-709,15,45880,1,8
65882,16000,16000.00,0.1409,60,home_improvement,0.2154,MD,OWN,8903.25,740-744,18,18898,1,10
55610,10000,10000.00,0.1399,36,debt_consolidation,0.0489,PA,MORTGAGE,2166.67,680-684,4,4544,0,10
38576,6000,6000.00,0.1242,36,major_purchase,0.1666,NJ,RENT,3500.00,675-679,8,7753,0,5
3116,9000,5242.75,0.1379,36,debt_consolidation,0.0676,NY,RENT,3875.00,670-674,7,7589,0,10

In [ ]:
type(raw_data['Loan.Length'][:1])

In [ ]:
def fix_data(raw_data):
       
    # clean interest rate using regex - ability to replace so df objects are mutable
    raw_data['Interest.Rate'] = [float(re.search('^[0-9]*.[0-9]*',loan).group(0))/100 for loan in raw_data['Interest.Rate']]

    # clean fico range and get score 
    raw_data['FICO.Score'] = map(lambda x: int(x.split('-')[0]), raw_data['FICO.Range'])
    
    # clean loan length
    raw_data['Loan.Length'] = map(lambda x: int(x.split()[0]), raw_data['Loan.Length'])
    
    # clean debt to income ratio
    raw_data['Debt.To.Income.Ratio'] = [float(re.search('^[0-9]*.[0-9]*',loan).group(0))/100 for loan in raw_data['Debt.To.Income.Ratio']]
    
    # add rate flag
    loan_data['IR_TF'] = [IR_Flag(rate) for index, rate in loan_data['Interest.Rate'].iteritems()]
    
    # add constant
    loan_data['Constant'] = [1 for row in loan_data.iterrows()]
    
    return raw_data

In [ ]:
raw_data.head()

In [ ]:
 # clean debt to income ratio
raw_data['Debt.To.Income.Ratio'] = [float(re.search('^[0-9]*.[0-9]*',loan).group(0) for loan in raw_data['Debt.To.Income.Ratio']]

In [ ]:
raw_data.head()

In [ ]:
raw_data.head()

In [24]:
loan_data = fix_data(raw_data)

ValueError: invalid literal for float(): 4%

In [8]:
raw_data.head()

In [10]:
ind_vars = list(loan_data.columns.values)

In [12]:
ind_vars.remove('Interest.Rate')

In [16]:
ind_vars.remove('IR_TF')

ValueError: list.remove(x): x not in list

In [ ]:
ind_vars.remove('Constant')

In [14]:
ind_vars

['Amount.Requested',
 'Amount.Funded.By.Investors',
 'Loan.Length',
 'Loan.Purpose',
 'Debt.To.Income.Ratio',
 'State',
 'Home.Ownership',
 'Monthly.Income',
 'FICO.Range',
 'Open.CREDIT.Lines',
 'Revolving.CREDIT.Balance',
 'Inquiries.in.the.Last.6.Months',
 'Employment.Length',
 'FICO.Score',
 'Constant']